name: TennisFetcher Hourly Sync

on:
  schedule:
    - cron: '0 * * * *' # Tourne toutes les heures à la minute 0
  workflow_dispatch: # Permet de cliquer sur un bouton pour forcer l'exécution

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # Accélère l'exécution en mettant les dépendances en cache

      - name: Installation des paquets
        run: pip install -r requirements.txt

      - name: Lancement de TennisFetcher
        env:
          SPORTSDB_SESSION: ${{ secrets.SPORTSDB_SESSION }}
        run: python main.py